config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # provide the routes for the API here
      get 'investigations', to: 'investigations#index', as: :investigations
      get 'investigations/:id', to: 'investigations#detail', as: :investigations_detail
      post 'investigations/:id/notes', to: 'investigations#new_note', as: :investigations_note
      post 'investigations/:id/add_assignment', to: 'investigations#add_assignment', as: :add_assignment
      put 'end_assignment/:id', to: 'investigations#end_assignment', as: :end_assignment
      put 'drop_suspect/:id', to: 'investigations#drop_suspect', as: :drop_suspect
      get 'crimes', to: 'investigations#crimes', as: :all_crimes
      get 'officers', to: 'investigations#officer_search', as: :search_officers
      get 'criminals', to: 'investigations#criminals_search', as: :search_criminals
      post 'investigations/:id/suspects', to: 'investigations#new_suspect', as: :new_investigation_suspect
      post 'investigations/:id/crime_investigations', to: 'investigations#new_crime_investigation', as: :new_crime_investigation
      put 'investigations/:id', to: 'investigations#update', as: :update_investigation_detail
      delete 'investigations/:id/crimes/:crime_id', to: 'investigations#delete_crime_investigation', as: :delete_investigation_crime

      # Routes for earlier API; disabled for React useage (some overlap)
      # get 'units', to: 'units#index', as: :units
      # get 'criminals/enhanced', to: 'criminals#enhanced', as: :enhanced_criminals
      # get 'officers/:id', to: 'officers#show', as: :officer
      # get 'investigations/:id', to: 'investigations#show', as: :investigation

    end
  end

  # Routes for regular HTML views go here...
    # Semi-static page routes
    get 'home', to: 'home#index', as: :home
    get '/about', to: 'home#about', as: :about
    get '/contact', to: 'home#contact', as: :contact
    get '/privacy', to: 'home#privacy', as: :privacy

    # Authentication routes
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    get 'officers/new', to: 'officers#new', as: :signup
    get 'officer/edit', to: 'officers#edit', as: :edit_current_officer


    # Resource routes (maps HTTP verbs to controller actions automatically):
    resources :units
    resources :sessions
    resources :officers
    resources :crimes
    resources :criminals
    resources :investigations do
      member do
        patch 'close'
      end
    end
    resources :sessions
    resources :home
    resources :users

    # Routes for assignments
    get 'assignments/new', to: 'assignments#new', as: :new_assignment
    post 'assignments/create', to: 'assignments#create', as: :assignments
    patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment


    # Routes for crime_investigations
    get 'crime_investigations/new/:investigation_id', to: 'crime_investigations#new', as: :new_crime_investigation
    post 'crime_investigations', to: 'crime_investigations#create', as: :crime_investigations
    delete 'crime_investigations/:id', to: 'crime_investigations#destroy', as: :remove_crimes


    # Routes for investigation_notes
    resources :investigation_notes, only: [:create]
    get 'investigation_notes/new/:investigation_id', to: 'investigation_notes#new', as: :new_investigation_note


    # Other custom routes
    get 'investigations/:investigation_id/suspects/new', to: 'suspects#new', as: :new_suspect
    post 'suspects', to: 'suspects#create'
    patch 'suspects/:id/terminate', to: 'suspects#terminate', as: :terminate_suspect


    # You can have the root of your site routed with 'root'
    root 'home#index'

end

app/models/officer.rb
class Officer < ApplicationRecord
  # because officers have to log into the system
  has_secure_password

  # Modules to extend functionality
  include Validations
  include OfficerAuthentication
  include Activeable::InstanceMethods
  extend Activeable::ClassMethods

  # Relationships
  belongs_to :unit
  has_many :assignments
  has_many :investigations, through: :assignments
  has_many :investigation_notes
  attr_accessor :destroyable

  # Enums
  enum :role, { officer: 1, chief: 2, commish: 3 }, scopes: true, default: :officer, suffix: true

  # Scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :for_unit, -> (unit_id){ where(unit_id: unit_id) }
  scope :detectives, -> { where('rank LIKE ?', "%detective%") }
  scope :search, ->(term) { where('first_name LIKE ? OR last_name LIKE ?', "#{term}%", "#{term}%") }
  
  # Validations
  validates_presence_of :first_name, :last_name, :unit_id, :role
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: "should be 9 digits and delimited with dashes only"
  validates_uniqueness_of :ssn
  validates_inclusion_of :rank, in: %w[Officer Sergeant Detective Detective\ Sergeant Lieutenant Captain Commissioner], message: "is not an option", allow_blank: true
  validate -> { is_active_in_system(:unit) }

  validates_inclusion_of :role, in: %w[officer chief commish], message: "is not an option"
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: 'does not match'
  validates_length_of :password, minimum: 4, message: 'must be at least 4 characters long', allow_blank: true

  # Other methods
  RANKS_LIST = [['Officer', 'Officer'],['Sergeant', 'Sergeant'],['Detective', 'Detective'],['Detective Sergeant', 'Detective Sergeant'],['Lieutenant', 'Lieutenant'],['Captain', 'Captain'],['Commissioner', 'Commissioner']].freeze

  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignments
    current = self.assignments.select{|a| a.end_date.nil?}
    return nil if current.empty?
    current
  end

  # Callbacks
  before_save    -> { strip_nondigits_from(:ssn) }

  include OfficerDeletion
  before_destroy -> { handle_deletion_request() }
  # after_rollback -> { handle_deletion_failure() }
  before_save    -> { remove_assignments_from_inactive_officer() }
end

app/controllers/officers_controller.rb
class OfficersController < ApplicationController
  before_action :set_officer, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    @active_officers = Officer.where(active: true).alphabetical.paginate(page: params[:page]).per_page(15)
    @inactive_officers = Officer.where(active: false).paginate(page: params[:page]).per_page(10)
  end

  def new
    @officer = Officer.new
  end

  def create
    @officer = Officer.new(officer_params)
    if @officer.save
      flash[:notice] = "Successfully created #{@officer.proper_name}."
      redirect_to officer_path(@officer)
    else
      render :new
    end
  end

  def show
    @current_assignments = @officer.assignments.where('end_date IS NULL OR end_date > ?', Date.today)
    @past_assignments = @officer.assignments.where('end_date <= ?', Date.today)
  end

  def edit
  end

  def update
    if @officer.update(officer_params)
      # successful update
      redirect_to officer_path(@officer)
    else
      # failed update
      render :edit
    end
  end

  def destroy
    if @officer.assignments.any?
      render :show
    else
      @officer.destroy
      flash[:notice] = "Removed #{@officer.proper_name} from the system."
      redirect_to officers_path
    end
  end

  private
  def set_officer
    @officer = Officer.find(params[:id])
  end

  def officer_params
    params.require(:officer).permit(:active, :ssn, :rank, :first_name, :last_name, :unit_id, :username, :role, :password, :password_confirmation)
  end
end

app/views/officers/_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :rank, collection: Officer::RANKS_LIST, label_html: { class: 'active' } %>
<%= f.association :unit, label_html: { class: 'active' } %>
<%= f.input :ssn, label_html: { class: 'active' } %> 
<%= f.input :role, collection: OfficerAuthentication::ROLES, label_html: { class: 'active' } %>
<%= f.input :username, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>

app/views/officers/edit.html.erb
<%= render partial: "partials/form_structure", locals: { object: @officer, 
                                                        type_of_form: "Edit Officer",
                                                        fields: "fields" } %>

app/views/officers/index.html.erb
<h4>Active Officers in GCPD</h4>
<table class="striped highlight">
  <thead>
    <th>Name</th>
    <th>Rank</th>
    <th class="align_center">Options</th>
  </thead>
  <% for officer in @active_officers %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to officer.name, officer_path(officer) %></td>
      <td><%= officer.rank %></td>
    </tr>   
  <% end %>
</table>
<br />
  <%= will_paginate @active_officers, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>

<p><strong>
<%= link_to "New Officer", new_officer_path, class: 'waves-effect waves-light btn' %> 
</strong></p>

app/views/officers/new.html.erb
<%= render partial: "partials/form_structure", locals: { object: @officer, 
                                                        type_of_form: "New Officer",
                                                        fields: "fields" } %>

app/views/officers/show.html.erb
<h4><%="Officer Information for " + @officer.proper_name%></h4>
<div class="card yellow lighten-4">
  <div class="card-content">
    <b>Current unit:&nbsp;&nbsp;</b><br>
      <%= @officer.unit.name %><br>

    <b>Current rank:&nbsp;&nbsp;</b><br>
      <%= @officer.rank %><br>

    <b>SSN:&nbsp;&nbsp;</b><br>
      <%= @officer.ssn.insert(3, '-').insert(6, '-') %><br>

    <b>Active duty?&nbsp;&nbsp;</b><br>
      <%= @officer.active ? "Yes" : "No" %><br>
    
    <%# create a current assignment card that displays all the current assignments of this officer%>
    <% unless @current_assignments == nil or @current_assignments.empty? %>
      <div class="card" id="current_assignments">
        <div class="card-content">
          <b>Current Assignments&nbsp;&nbsp;</b><br>
            <ul>
              <% for a in @current_assignments do %>
                <li><%= "Starting" %> </li><br>
                <li><%= a.investigation.title%></li> 
              <% end %>
            </ul>
          <br>
        </div>
      </div>
    <% end %>
    
    <% unless @past_assignments == nil or @past_assignments.empty? %>
      <div class="card" id="past_assignments">
        <div class="card-content">
          <b>Past Assignments&nbsp;&nbsp;</b><br>
            <ul>
              <% for a in @past_assignments do %>
                <li><%= "Ending" %> </li><br>
                <li><%= a.investigation.title%></li> 
              <% end %>
            </ul>
            <br>
        </div>
      </div>
    <% end %>
    <br>
    <p><strong>
      <%= link_to "Add a new assignment", new_assignment_path(officer_id: @officer.id), class: 'waves-effect waves-light btn' %>
    </strong></p>
</div>