config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # provide the routes for the API here
      get 'investigations', to: 'investigations#index', as: :investigations
      get 'investigations/:id', to: 'investigations#detail', as: :investigations_detail
      post 'investigations/:id/notes', to: 'investigations#new_note', as: :investigations_note
      post 'investigations/:id/add_assignment', to: 'investigations#add_assignment', as: :add_assignment
      put 'end_assignment/:id', to: 'investigations#end_assignment', as: :end_assignment
      put 'drop_suspect/:id', to: 'investigations#drop_suspect', as: :drop_suspect
      get 'crimes', to: 'investigations#crimes', as: :all_crimes
      get 'officers', to: 'investigations#officer_search', as: :search_officers
      get 'criminals', to: 'investigations#criminals_search', as: :search_criminals
      post 'investigations/:id/suspects', to: 'investigations#new_suspect', as: :new_investigation_suspect
      post 'investigations/:id/crime_investigations', to: 'investigations#new_crime_investigation', as: :new_crime_investigation
      put 'investigations/:id', to: 'investigations#update', as: :update_investigation_detail
      delete 'investigations/:id/crimes/:crime_id', to: 'investigations#delete_crime_investigation', as: :delete_investigation_crime

      # Routes for earlier API; disabled for React useage (some overlap)
      # get 'units', to: 'units#index', as: :units
      # get 'criminals/enhanced', to: 'criminals#enhanced', as: :enhanced_criminals
      # get 'officers/:id', to: 'officers#show', as: :officer
      # get 'investigations/:id', to: 'investigations#show', as: :investigation

    end
  end

  # Routes for regular HTML views go here...
    # Semi-static page routes
    get 'home', to: 'home#index', as: :home
    get '/about', to: 'home#about', as: :about
    get '/contact', to: 'home#contact', as: :contact
    get '/privacy', to: 'home#privacy', as: :privacy

    # Authentication routes
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    get 'officers/new', to: 'officers#new', as: :signup
    get 'officer/edit', to: 'officers#edit', as: :edit_current_officer


    # Resource routes (maps HTTP verbs to controller actions automatically):
    resources :units
    resources :sessions
    resources :officers
    resources :crimes
    resources :criminals
    resources :investigations do
      member do
        patch 'close'
      end
    end
    resources :sessions
    resources :home
    resources :users

    # Routes for assignments
    get 'assignments/new', to: 'assignments#new', as: :new_assignment
    post 'assignments/create', to: 'assignments#create', as: :assignments
    patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment


    # Routes for crime_investigations
    get 'crime_investigations/new/:investigation_id', to: 'crime_investigations#new', as: :new_crime_investigation
    post 'crime_investigations', to: 'crime_investigations#create', as: :crime_investigations
    delete 'crime_investigations/:id', to: 'crime_investigations#destroy', as: :remove_crimes


    # Routes for investigation_notes
    resources :investigation_notes, only: [:create]
    get 'investigation_notes/new/:investigation_id', to: 'investigation_notes#new', as: :new_investigation_note


    # Other custom routes
    get 'investigations/:investigation_id/suspects/new', to: 'suspects#new', as: :new_suspect
    post 'suspects', to: 'suspects#create'
    patch 'suspects/:id/terminate', to: 'suspects#terminate', as: :terminate_suspect


    # You can have the root of your site routed with 'root'
    root 'home#index'

end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.humanize %></strong>
  <% end %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <p><%= msg %></p>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About GCPD', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact GCPD', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("ericlin2@andrew.cmu.edu", "Eric Lin", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2024
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-4 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>

app/views/partials/_nav.html.erb
<nav id="nav" class="grey darken-1">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <% if logged_in? %>
        <li><%= link_to 'Investigations', investigations_path %></li>
        <li><%= link_to 'Officers', officers_path %></li>
        <li><%= link_to 'Units', units_path %></li>
      <% end %>
    </ul>
    <ul class="right">
      <% if logged_in? %>
        <li><%= link_to 'Logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.humanize }" %>

<div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All
    <% end %>
    &nbsp;&nbsp;
  
  <% if controller.respond_to?(:update) && can?(:update, object) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if controller.respond_to?(:destroy) && can?(:destroy, object) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

  <% if controller.respond_to?(:close) && can?(:close, object) %>
    <%= link_to(eval("close_#{model_name}_path(object)"), method: 'patch', data: {confirm: "Are you sure you want to close this #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Close #{opt}" %>
    <% end %>
  <% end %>

  <% if controller.respond_to?(:terminate) && can?(:terminate, object) %>
    <%= link_to(eval("terminate_#{model_name}_path(object)"), method: 'patch', data: {confirm: "Are you sure you want to terminate this #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Terminate #{opt}" %>
    <% end %>
  <% end %>
</div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>
  <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_topbar.html.erb
<div class ="grey darken-3">
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
  </div>
  <div class="col s10">
    <h3 class="white-text">GCPD Tracking System</h3>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>
<div class ="grey darken-3">