config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # provide the routes for the API here
      get 'investigations', to: 'investigations#index', as: :investigations
      get 'investigations/:id', to: 'investigations#detail', as: :investigations_detail
      post 'investigations/:id/notes', to: 'investigations#new_note', as: :investigations_note
      post 'investigations/:id/add_assignment', to: 'investigations#add_assignment', as: :add_assignment
      put 'end_assignment/:id', to: 'investigations#end_assignment', as: :end_assignment
      put 'drop_suspect/:id', to: 'investigations#drop_suspect', as: :drop_suspect
      get 'crimes', to: 'investigations#crimes', as: :all_crimes
      get 'officers', to: 'investigations#officer_search', as: :search_officers
      get 'criminals', to: 'investigations#criminals_search', as: :search_criminals
      post 'investigations/:id/suspects', to: 'investigations#new_suspect', as: :new_investigation_suspect
      post 'investigations/:id/crime_investigations', to: 'investigations#new_crime_investigation', as: :new_crime_investigation
      put 'investigations/:id', to: 'investigations#update', as: :update_investigation_detail
      delete 'investigations/:id/crimes/:crime_id', to: 'investigations#delete_crime_investigation', as: :delete_investigation_crime

      # Routes for earlier API; disabled for React useage (some overlap)
      # get 'units', to: 'units#index', as: :units
      # get 'criminals/enhanced', to: 'criminals#enhanced', as: :enhanced_criminals
      # get 'officers/:id', to: 'officers#show', as: :officer
      # get 'investigations/:id', to: 'investigations#show', as: :investigation

    end
  end

  # Routes for regular HTML views go here...
    # Semi-static page routes
    get 'home', to: 'home#index', as: :home
    get '/about', to: 'home#about', as: :about
    get '/contact', to: 'home#contact', as: :contact
    get '/privacy', to: 'home#privacy', as: :privacy

    # Authentication routes
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    get 'officers/new', to: 'officers#new', as: :signup
    get 'officer/edit', to: 'officers#edit', as: :edit_current_officer


    # Resource routes (maps HTTP verbs to controller actions automatically):
    resources :units
    resources :sessions
    resources :officers
    resources :crimes
    resources :criminals
    resources :investigations do
      member do
        patch 'close'
      end
    end
    resources :sessions
    resources :home
    resources :users

    # Routes for assignments
    get 'assignments/new', to: 'assignments#new', as: :new_assignment
    post 'assignments/create', to: 'assignments#create', as: :assignments
    patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment


    # Routes for crime_investigations
    get 'crime_investigations/new/:investigation_id', to: 'crime_investigations#new', as: :new_crime_investigation
    post 'crime_investigations', to: 'crime_investigations#create', as: :crime_investigations
    delete 'crime_investigations/:id', to: 'crime_investigations#destroy', as: :remove_crimes


    # Routes for investigation_notes
    resources :investigation_notes, only: [:create]
    get 'investigation_notes/new/:investigation_id', to: 'investigation_notes#new', as: :new_investigation_note


    # Other custom routes
    get 'investigations/:investigation_id/suspects/new', to: 'suspects#new', as: :new_suspect
    post 'suspects', to: 'suspects#create'
    patch 'suspects/:id/terminate', to: 'suspects#terminate', as: :terminate_suspect


    # You can have the root of your site routed with 'root'
    root 'home#index'

end

app/models/unit.rb
class Unit < ApplicationRecord
  include Activeable::InstanceMethods
  extend Activeable::ClassMethods

  # Relationships
  has_many :officers
  has_many :assignments, through: :officers

  # Scopes
  scope :alphabetical, -> { order('name') }
  
  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # Other methods
  def number_of_active_officers
    self.officers.active.count
  end

  def number_of_unique_open_investigations
    self.officers.map{|o| o.investigations.is_open}.flatten.uniq.count
  end

  def number_of_unique_closed_investigations
    self.officers.map{|o| o.investigations.is_closed}.flatten.uniq.count
  end

  def number_of_unique_investigations_involving_batman
    self.officers.map{|o| o.investigations.with_batman}.flatten.uniq.count
  end

  # Callback - to handle destroying units
  before_destroy do 
    check_if_any_officers_in_unit
    if errors.present?
      throw(:abort)
    end
  end

  private
  def check_if_any_officers_in_unit
    unless self.officers.empty?
      errors.add(:base, "Unit cannot be deleted because officers are listed as unit members.")
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    @active_units = Unit.where(active: true)
    @inactive_units = Unit.where(active: false)
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      flash[:notice] = "Successfully added #{@unit.name} to GCPD."
      redirect_to units_path
    else
      render :new
    end
  end

  def show
    @unit = Unit.find(params[:id])
    @officers = @unit.officers.active.alphabetical.paginate(page: params[:page]).per_page(10)
  end

  def edit
  end

  def update
    @unit = Unit.find(params[:id])
    if @unit.update(unit_params)
      flash[:notice] = "Updated unit information"
      redirect_to unit_path(@unit)
    else
      render :edit
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    if @unit.destroy
      flash[:notice] = "Removed #{@unit.name} from the system."
      redirect_to units_path
    else
      render :index
    end
  end

  private
  def set_unit
    @unit = Unit.find(params[:id])
  end

  def unit_params
    params.require(:unit).permit(:name, :active)
  end
end

app/views/units/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>

app/views/units/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @unit, 
                                                        type_of_form: "Edit Unit",
                                                        fields: "fields"} %>

app/views/units/index.html.erb
<h4>Active Units in GCPD</h4>
<table class="striped highlight">
  <thead>
    <th>Unit</th>
    <th>Active</th>
  </thead>
  <% if @active_units != nil %>
    <% for unit in @active_units.alphabetical %>
        <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
        <td><%= link_to unit.name, unit_path(unit) %></td>
        <td><%= unit.active ? "Yes" : "No" %></td>
        </tr>   
    <% end %>
  <% end %>
</table>

<p>&nbsp;</p>

<p><strong>
<%= link_to "New Unit", new_unit_path, class: 'waves-effect waves-light btn' %> 
</strong></p>

app/views/units/new.html.erb
<%= render partial: "partials/form_structure", locals: { object: @unit, 
                                                        type_of_form: "New Unit",
                                                        fields: "fields" } %>

app/views/units/show.html.erb
<div class="card" id="officers">
  <div class="card-content">
    <span class="card-title"><%= @unit.name %></span>
    <% if @officers.empty? %>
      <p>There are no active officers currently in this unit</p>
    <% else %>
     <p>Active Officers in <%=@unit.name%> Unit</p>
      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Rank</th>
          <th>Active Assignments</th>
        </thead>
        <% for o in @officers.alphabetical %>
          <tr>
            <td><%= o.name %></td>
            <td><%= o.rank %></td>
            <td><%= o.assignments.current.count %></td>
          </tr>
        <% end %>
      </table>
      <%# create a pagination for the officers in this unit%>
      <br />
      <%= will_paginate @officers, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next"%>
      <p>&nbsp;</p>
    <% end %>
  </div>
</div>

<div class="card" id="stats">
  <div class="card-content">
    <span class="card-title">Statistics for <%= @unit.name %> Unit</span>
    <b>Number of Active Officers:&nbsp;&nbsp;<b>
      <%= @unit.number_of_active_officers %><br /><br />
    <b>Number of Open Cases:&nbsp;&nbsp;</b>
      <%= @unit.number_of_unique_open_investigations %><br /><br />
    <b>Number of Closed Cases:&nbsp;&nbsp;</b>
      <%=  @unit.number_of_unique_closed_investigations %><br /><br />
    <b>Cases Involving Batman:&nbsp;&nbsp;<b>
      <%=  @unit.number_of_unique_investigations_involving_batman %><br /><br />
  </div>
</div>